namespace XerifeTv.CMS.Modules.BackgroundJobQueue.Enums;

public enum EBackgroundJobType
{
    REGISTER_SPREADSHEET_MOVIES,
    REGISTER_SPREADSHEET_SERIES,
    REGISTER_SPREADSHEET_CHANNELS,
    IMPORT_EPISODES_FROM_SERIES_IMDB,
    BATCH_ADD_MOVIES,
    BATCH_ADD_EPISODE_LINKS
}