namespace XerifeTv.CMS.Shared.Database.MongoDB;

public enum ECollection
{
    MOVIES,
    SERIES,
    CHANNELS,
    FRANCHISES,
    USERS,
    BACKGROUND_JOB_QUEUE,
    WEBHOOKS,
    MEDIA_DELIVERY_PROFILES,
    SYSTEM_SETTINGS,
    ACTIVITIES,
    SITE_USERS,
    SITE_ROLES,
    SITE_WATCH_PROGRESS
}
